from maze_env.wrappers.clip_reward import ClipReward
from maze_env.wrappers.discrete_actions import DiscreteActions
from maze_env.wrappers.reacher_weighted_reward import ReacherRewardWrapper
from maze_env.wrappers.relative_position import RelativePosition
